### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by patcon** [janimo/textsecure-docker#1]
Just wanted to say thanks for sharing this on the list! I've got a similar effort, but assuming folks want to use Chef to manage their infra:

https://github.com/patcon/chef-textsecure

Thoughts on putting our repos in a common place, since the devs don't want this sort of stuff in the main whispersystem repo? Maybe whispersystems-support or something, for tools to support those who want to host their own stuff for whatever reason

**Comment by janimo** [comment]
I think we can link from the textsecure-server wiki to both repos, there are guides there on setting up a server.
cheers

**Comment by patcon** [comment]
Hm. I'm unsure that would be appreciated, but I guess we could ask

**Comment by janimo** [comment]
It's a wiki. If someone will deem the info inappropriate they can delete it.
https://github.com/WhisperSystems/TextSecure-Server/wiki
