### ISSUE TITLE
Doc on gencerts - is it wrong?

### ISSUE THREAD

**Issue by jeff-r-skillrev** [janimo/textsecure-docker#2]
Maybe this is obvious to the rest of the world, but I struggled to run gencerts with the $ALTNAME environment variable set. Your instructions set a shell variable, but in order for child processes to get that value, you have to export it and make it an environment variable.

Maybe you should break that into 3 lines in the doc, like this:
ALTNAME=IP:10.0.0.1
export ALTNAME
./gencerts

I couldn't get gencerts to succeed until I had ran "export ALTNAME".

And thanks for an easy way to run TextSecure Server!

**Comment by janimo** [comment]
Are you sure ALTNAME is not set? What shell are you using?
Setting a variable on the command line should have the effect of exporting it to that command.
See if you put echo $ALTNAME && exit as the first line in gencerts

**Comment by jeff-r-skillrev** [comment]
I'm just using good ole' bash. Maybe I did something wrong...it does seem to work. When I change it to echo in the first line of the script and exit, I see the value.
